[build]
  publish = "dist"
  command = "cd client && npx vite build --outDir ../dist"

[dev]
  command = "npx vite --port 3000 --host"
  targetPort = 3000
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"