[build]
  publish = "client/dist"
  command = "cd client && npm install && npx vite build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"